### ISSUE TITLE
StrcutMask error - output is generated in rawdata dir (not derivatives dir)

### ISSUE THREAD

**Issue by mdibiase1** [pnlbwh/luigi-pnlpipe#38]
Hi there,

The first output to --task StructMask (sub-*_desc-Xc_T2w.nii.gz) is generated in the bids-data-dir instead of the bids-data-dir/derivatives dir. This triggers the AttributeError: Multiple files exist with the template /home/pnlbwh/myData/sub-100206/anat/*_T2w.nii.gz Please provide a unique representative template.

I have tried specifying both paths (rawdata and derivatives) as below which doesn't help.

/home/pnlbwh/luigi-pnlpipe/workflows/ExecuteTask.py --bids-data-dir /home/pnlbwh/myData/rawdata -c ${1} -s 1 --t2-template sub-*/anat/*_T2w.nii.gz --task StructMask --derivatives-name /home/pnlbwh/myData/derivatives/pnlpipe

Just for context -- I am running this code in Singularity on a different cluster

Thanks,

Maria

**Comment by tashrifbillah** [comment]
Changes made:

* we have removed the `/home/pnlbwh/.bashrc source statement from singularity script
* removed a previous `*desc-Xc_T2.nii.gz` that was in the same directory of `*_T2.nii.gz`
* removed `--derivatives-name /home/pnlbwh/myData/derivatives/pnlpipe`

Things appear to be working fine now :)
