### ISSUE TITLE
Path to example config files

### ISSUE THREAD

**Issue by monicalyons** [pnlbwh/luigi-pnlpipe#7]
In `luigi-pnlpipe/workflows/run_luigi_pnlpipe.lsf` line 11, path to config example should be `/data/pnl/soft/pnlpipe3/luigi-pnlpipe/params/*.cfg` (currently `/data/pnl/soft/pnlpipe3/luigi-pnlpipe/scripts/params/*.cfg`)

**Comment by tashrifbillah** [comment]
Thanks!
